# Generated by Django 5.1.1 on 2024-09-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "data_criacao",
                    models.DateField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pendente", "Pendente"), ("concluida", "Concluída")],
                        default="pendente",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarefa",
                "verbose_name_plural": "Tarefas",
            },
        ),
    ]
