# Generated by Django 5.1.1 on 2024-09-22 21:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tarefas", "0003_alter_tarefa_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tarefa",
            name="descricao",
        ),
    ]
