# Generated by Django 5.1.1 on 2024-09-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tarefas", "0004_remove_tarefa_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="descricao",
            field=models.TextField(default="1", verbose_name="Descrição"),
        ),
    ]
