# Generated by Django 5.1.1 on 2024-09-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tarefas", "0005_tarefa_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefa",
            name="descricao",
            field=models.TextField(verbose_name="Descrição"),
        ),
    ]
