# Generated by Django 5.1.1 on 2024-09-23 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tarefas", "0006_alter_tarefa_descricao"),
        ("user", "0003_rename_is_autheticated_usuario_is_authenticated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefa",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.usuario"
            ),
        ),
    ]
