# Generated by Django 5.1.1 on 2024-09-24 01:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tarefas", "0007_alter_tarefa_user"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="tarefa",
            table="tarefas",
        ),
    ]
