# Generated by Django 5.1.1 on 2024-09-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tarefas", "0012_alter_tarefa_data_criacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefa",
            name="data_criacao",
            field=models.DateField(verbose_name="Criado em"),
        ),
    ]
