# Generated by Django 5.1.1 on 2024-09-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="is_autheticated",
            field=models.BooleanField(default=False, verbose_name="Autenticado"),
        ),
    ]
