# Generated by Django 5.1.1 on 2024-09-23 23:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_usuario_is_autheticated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="is_autheticated",
            new_name="is_authenticated",
        ),
    ]
